### ISSUE TITLE
Reversing tiktok API.

### ISSUE THREAD

**Issue by sheldygg** [Evil0ctal/Douyin_TikTok_Download_API#338]
I have question. Which endpoint I must reverse for find endpoint which used in your code?
Now this endpoint is not working, and you are not responding to issues, if I knew how to find a new endpoint, I would make a pull request.
How i can find the same endpoint but working?

**Comment by GoddessOfSwords** [comment]
You can find these api and api endpoinys by researching their .apk, or website or application network activity. (api located in the code of this repository can be found by exploring the .apk file)

However, it will be difficult to find a “working api endpoint”, since all endpoints found have stopped working (possibly due to TikTok restrictions or their restriction in the USA or a change in the api system)
 
You can try to find other apis to get information from aweme and share with us or wait for someone else to try it.

Also, if it is useful to someone, there are 1 more strange working endpoint, it returned information twice out of 100 requests after useast2a was disabled. (maybe it was cached information):
api22-normal-c-alisg.tiktokv.com

**Comment by Evil0ctal** [comment]
TikTok had been change lot recently and most API from app now requires the sign header for the request, I will try fix it soon.

**Comment by MaximeOLIVA** [comment]
> TikTok had been change lot recently and most API from app now requires the sign header for the request, I will try fix it soon.

What do we need to put inside of the sign header ?

**Comment by Evil0ctal** [comment]
X-A,X-G,X-K,X-L

**Comment by MaximeOLIVA** [comment]
Is there a way to generate it ?

**Comment by jgore077** [comment]
> X-A,X-G,X-K,X-L

What does this mean?

**Comment by sheldygg** [comment]
Now my code is working:
https://github.com/sheldygg/aiotiktok

**Comment by MaximeOLIVA** [comment]
> Now my code is working: https://github.com/sheldygg/aiotiktok

How did you get the iid param ?

**Comment by Evil0ctal** [comment]
Hi I just make a new realease fixed this issue, please see the note below:

https://github.com/Evil0ctal/Douyin_TikTok_Download_API/releases/tag/V3.2.1

Thank you all, and have a nice day ❤️
